# Generated by Django 3.2.6 on 2021-08-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codewazlar', '0002_remove_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
