# Generated by Django 3.2.6 on 2021-08-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codewazlar', '0006_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='slider',
            name='title1',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title2',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title3',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title4',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
